# Generated by Django 5.2.12 on 2026-04-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('att_sessions', '0002_alter_attendancesession_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together=set(),
        ),
    ]
