# Generated by Django 4.2.29 on 2026-03-20 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('att_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webgl_hash', models.CharField(max_length=64)),
                ('reason', models.CharField(choices=[('already_marked', 'Already Marked'), ('device_conflict', 'Device Conflict')], max_length=30)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('attempted_by_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proxy_attempts', to='departments.studentprofile')),
                ('conflicting_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxy_conflicts', to='departments.studentprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_logs', to='att_sessions.attendancesession')),
            ],
        ),
        migrations.CreateModel(
            name='WebGLFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=64)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='att_sessions.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fingerprints', to='departments.studentprofile')),
            ],
            options={
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='absent', max_length=20)),
                ('marked_by', models.CharField(choices=[('default', 'Default'), ('qr', 'QR Scan'), ('manual', 'Manual')], default='default', max_length=20)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='att_sessions.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='departments.studentprofile')),
            ],
            options={
                'unique_together': {('session', 'student')},
            },
        ),
    ]
