# Generated by Django 4.2.29 on 2026-03-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webglfingerprint',
            old_name='hash',
            new_name='webgl_hash',
        ),
    ]
