# Generated by Django 5.2.12 on 2026-04-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_hash_webglfingerprint_webgl_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='distance',
            field=models.FloatField(blank=True, help_text='Distance from teacher in meters', null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='proxylog',
            name='attempted_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='proxylog',
            name='attempted_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='proxylog',
            name='reason',
            field=models.CharField(choices=[('already_marked', 'Already Marked'), ('device_conflict', 'Device Conflict'), ('location_mismatch', 'Location Mismatch'), ('location_denied', 'Location Denied')], max_length=30),
        ),
    ]
